FROM node:22-bookworm AS builder

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

COPY . .

RUN npm run build

# Serve os arquivos diretamente com o Node.js
FROM node:22-bookworm

WORKDIR /app

# Copia os arquivos compilados para o diretório /app
COPY --from=builder /app/web/dist .

# Expor a porta que o servidor vai rodar
EXPOSE 3000

# Instalar o http-server ou qualquer servidor de arquivos estáticos
RUN npm install -g http-server

# Iniciar o servidor
CMD ["http-server", "dist", "-p", "3000"]