FROM node:22-bookworm AS builder

WORKDIR /app

COPY package.json package-lock.json ./ 

RUN npm install

COPY . .

RUN npm run build

FROM nginx:stable-alpine

WORKDIR /usr/share/nginx/html

RUN rm -rf ./*

COPY --from=builder /app/dist .

# Expondo a porta 3000
EXPOSE 5173  

CMD ["nginx", "-g", "daemon off;"]